name: Deploy

on:
  push:
    branches:
      - main

jobs:
  create_artifact:
    runs-on: ubuntu-latest
    name: Create Artifact
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ls
        run: |
          ls
        working-directory: ${{ github.workspace }}
      
      - name: Copy all files to docs except .github
        run: |
          mkdir docs
          cp -r * docs
          rm -rf docs/.github
      
      - name: Archive production build
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: ${{ github.workspace}}/docs

  clone_repo:
    runs-on: ubuntu-latest
    name: Clone Repo
    steps:
      - name: clone_quartz
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          repository: 'quartz'
          branch: 'main'
          owner: 'jackyzha0'

      - name: remove docs folder
        run: |
          rm -rf docs
        working-directory: ${{ github.workspace }}

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: docs
        
