name: Deploy

on:
  push:
    branches:
      - main

jobs:
  create_artifact:
    runs-on: ubuntu-latest
    name: Create Artifact
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Archive production build
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: ${{ github.workspace}}

  clone_repo:
    needs: create_artifact
    runs-on: ubuntu-latest
    name: Clone Repo
    steps:
      - name: clone_quartz
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          repository: "quartz"
          branch: "v4"
          owner: "jackyzha0"
          depth: 1

      - name: remove docs folder
        run: |
          rm -rf quartz/docs
        working-directory: ${{ github.workspace }}

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: ${{ github.workspace }}/quartz
      
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ${{ github.workspace }}/quartz

  test:
    needs: clone_repo
    runs-on: ubuntu-latest
    name: Test before
    strategy:
      fail-fast: false 
      matrix:
        node-version: [18.14, 18.16, 18.18]
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: ${{ github.workspace }}

      - name: Use NodeJs ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: |
          npm install
        working-directory: ${{ github.workspace }}/quartz

  build:
    needs: test
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: app

      - name: Use NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install
        working-directory: ${{ github.workspace }}/quartz

      - name: Build
        run: |
          npm run quartz build
        working-directory: ${{ github.workspace }}/quartz

      - name: Archive production build
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: ${{ github.workspace }}/quartz/public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: public
          path: ${{ github.workspace }}

      - name: list directory
        run: |
          ls -la
        working-directory: ${{ github.workspace }}/quartz/public

      - name: Deploy to cloudflare pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_PAGES_SITE }}
          projectName: ${{ secrets.CF_PAGES_PROJECT_NAME }}
          directory: ${{ github.workspace }}/quartz/public
      
      
