name: Deploy

on:
  push:
    branches:
      - main

jobs:
  create_artifact:
    runs-on: ubuntu-latest
    name: Create Artifact
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Archive production build
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: ${{ github.workspace}}

  clone_repo:
    needs: create_artifact
    runs-on: ubuntu-latest
    name: Clone Repo
    steps:
      - name: clone_quartz
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          repository: "quartz"
          branch: "v4"
          owner: "jackyzha0"
          depth: 1

      - name: remove docs folder
        run: |
          rm -rf quartz/docs
        working-directory: ${{ github.workspace }}

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: ${{ github.workspace }}/quartz
